### ISSUE TITLE
Extended text entities are truncated

### ISSUE THREAD

**Issue by Outback-Andy** [bremor/bureau_of_meteorology#236]
Long extended text forecast messages for sensor.xxx_extended_text_0 ~ 7 are truncated at 255 characters meaning important information about weather conditions could be missed.

<img width="555" alt="Screenshot 2024-09-06 at 6 25 47 AM" src="https://github.com/user-attachments/assets/2984c16c-d80c-4648-a0c0-2c2b01dfd94d">

From BoM website
<img width="359" alt="Screenshot 2024-09-06 at 6 34 29 AM" src="https://github.com/user-attachments/assets/8807666f-3e94-49d9-b8cb-506beba13e69">

**Comment by Schottburg** [comment]
@Outback-Andy I came here to post the same issue but have now found the solution. It's not an integration issue but a limit with templates in HA. 

You can pull the full state from attributes using a template sensor as the full text is stored in attributes. 

Put this in your configuration.yaml file (can't do this from the GUI yet as far as I know) replacing the sensor name with yours. 

Cheers!

```
template:
  - sensor:
      - name: "BoM Extended Text Full"
        unique_id: bom_extended_text_full
        state: "Full forecast in attributes"
        attributes:
          full_text: "{{ state_attr('sensor.armstrong_creek_extended_text_0', 'state') }}"
```


![Image](https://github.com/user-attachments/assets/b59ab180-13d0-4aff-acea-673c2179d864)
