### ISSUE TITLE
Severe weather alert 

### ISSUE THREAD

**Issue by bigwoof** [bremor/bureau_of_meteorology#37]
Hi @brenor,
It would great to have some sort of binary sensor for current weather warnings for example in Brisbane the bom product ID is IDQ21035 and the images on the ftp site are
IDQ21047.png
IDQ21041.png

Do you think that there is a way to be able to get this info into the custom component? 

I have a simple script that looks for the file on the ftp server and use that to check for warnings but it may be more efficient to pull it all into one component. And it may be helpful to other users too, eg roll up the blinds before a storm.

**Comment by bremor** [comment]
Thanks for the suggestion, https://weather.bom.gov.au/ does have weather warnings so i'm sure I could include this. I will have a crack at this in the next couple of weeks.

**Comment by pkeymeruu** [comment]
Thanks for looking into it!

**Comment by bigwoof** [comment]
I just noticed that some parts of Australia have a storm tracker, probably only around capital cities, for example, SEQ:
http://www.bom.gov.au/qld/forecasts/brisbane-thunderstorms.shtml

not sure if this is helpful information particularly since it is only for a small section of the country.

PS: the 0.9 update looks like it will add a lot of useful features! will update shortly

**Comment by bremor** [comment]
Just documenting my findings here...

https://api.weather.bom.gov.au/v1/locations/r3gx2f/warnings

`{"metadata":{"response_timestamp":"2020-12-28T05:02:19Z"},"data":[{"id":"NSW_PW005_IDN21033","type":"severe_thunderstorm_warning","title":"Severe Thunderstorm Warning for Sydney Metropolitan forecast district","short_title":"Severe Thunderstorm Warning","state":"NSW","warning_group_type":"major","issue_time":"2020-12-28T04:55:48Z","expiry_time":"2020-12-28T10:55:48.000Z","phase":"update"},{"id":"NSW_ME017_IDN21035","type":"severe_thunderstorm_warning","title":"Severe Thunderstorm Warning for New South Wales","short_title":"Severe Thunderstorm Warning","state":"NSW","warning_group_type":"major","issue_time":"2020-12-28T04:00:40Z","expiry_time":"2020-12-28T06:00:40.000Z","phase":"update"},{"id":"NSW_MW009_IDN20400","type":"marine_wind_warning","title":"Marine Wind Warning for New South Wales","short_title":"Marine Wind Warning","state":"NSW","warning_group_type":"major","issue_time":"2020-12-27T23:20:40Z","expiry_time":"2020-12-28T07:20:40.000Z","phase":"update"}]}`

**Comment by devonuto** [comment]
What happened to this?  Seems like an excellent inclusion for announcing warnings over smart devices/ shutting roller shutters/ garage doors.

**Comment by nixmaster2000** [comment]
Would definitely like to see a severe weather alert entity.

**Comment by StormyKnight17** [comment]
+1 for a severe weather alert entity

https://api.weather.bom.gov.au/v1/locations/r3gx2f/warnings
r3gx2f is the geohash for Sydney area.
Use http://geohash.co/ to enter gps coordinates & set to 6 digits to find the geohash for your area.

Once you have the response, you then need to be able to scrape the provided warning page to see if your town is mentioned (or a close major town). Some warning areas are quite big so a warning may not apply to you without the town information.

**Comment by glenn20** [comment]
PR #125 collects data from the warnings API and presents it through an optional "warnings" sensor. The state of the sensor is the number of warnings returned and the warnings data is available as a list from the "warnings" attribute on the sensor.

Comments and suggestions are welcome. Is this sufficient to address the request? It is not obvious what more to do with the data at this point.

**Comment by Makin-Things** [comment]
@glenn20  thanks for the PR. I merged it and then found a small problem. If I untick observation sensors I get an error.
![image](https://user-images.githubusercontent.com/91187456/168732893-e7fffa56-8018-4d2f-ad35-5c81d6786923.png)
I don't use the observation sensors as I get that data by other means.

**Comment by glenn20** [comment]
Ah - I thought I tested that - obviously not. Fix coming.

**Comment by glenn20** [comment]
OK - PR #126 has a bugfix. It appears I must have accidentally deleted a few important lines after testing and before commit. The config dialog for the forecast sensors should work now.

**Comment by Makin-Things** [comment]
It has been merged and now works as expected. Now to wait for some warnings to be issued for around here.

**Comment by glenn20** [comment]
Note that this PR makes the warnings data available (based on geohash location as described above). However, there is currently no logic to filter by `phase`, `warning_group_type` or `type`. That can be done with an automation or template sensors, etc... Some filter logic could be added to the integration, but it would be complicated to construct an intuitive and easy config_flow to do that at config time. Any suggestions welcome.

Data is collected from the BoM warnings API. The state of the sensor is the number of warnings and the warnings data is stored as a list in the "warnings" attribute of the sensor, eg:

```
sensor.melbourne_forecast_warnings:
- state: 1
- Attributes:
      response_timestamp: 2022-05-16T13:03:47Z
      copyright: This Application Programming Interface (API) is owned by the Bureau of Meteorology (Bureau). 
          You must not use, copy or share this API without express permission from the Bureau. Please contact us for more 
          information. Follow this link http://www.bom.gov.au/inside/contacts.shtml to view our contact details.
      attribution: Data provided by the Australian Bureau of Meteorology
      warnings: 
      - id: VIC_MW005_IDV20600
        type: marine_wind_warning
        title: Marine Wind Warning for Victoria
        short_title: Marine Wind Warning
        state: VIC
        warning_group_type: minor
        issue_time: '2022-05-16T12:00:00Z'
        expiry_time: '2022-05-16T19:00:00Z'
        phase: cancelled
      friendly_name: Melbourne Forecast Warnings
```
