### ISSUE TITLE
Showing status "Clear Night" during the day

### ISSUE THREAD

**Issue by austwhite** [bremor/bureau_of_meteorology#74]
I just installed this and tried to put the BOM weather.[location] as a card, and it is showing CLEAR NIGHT, yet it is 5:55pm, and sunset is not until 8:16pm.
I haven't used this long enough to see when it changes over, but this looks like a bug.
Home Assistant Version:
core-2021.2.3
supervisor-2021.02.9
Home Assistant OS 5.11
GPS Co-Ordinates:
Latitude: -37.7810 
Longitude: 144.8320

Thanks

**Comment by DavidFW1960** [comment]
Where do you see CLEAR NIGHT? Is that a state? What card are you using to display it?
This integration only reports what the BOM API reports

**Comment by austwhite** [comment]
@DavidFW1960 
On the Weather card if i insert weather.location into lovelace.  It also shows when checking states in Developer Tools.

I was not sure BOM actually sent Day/Night via the API.  I haven't checked though lately.  I somehow have a feeling they may not be getting their day and night wrong though.
That said, if there is anything I can do to check this and give more information, let me know

**Comment by DavidFW1960** [comment]
Can you show a screenshot of the appropriate place in dev-tools for that entity?

**Comment by bremor** [comment]
@austwhite 
When you see this again can you please paste the contents of the URLs:
https://api.weather.bom.gov.au/v1/locations/r1qcpd/observations
https://api.weather.bom.gov.au/v1/locations/r1f3pw/forecasts/daily

Can you please also take a copy/paste of the weather.location entity from with Developer Tools->States

**Comment by slx-io** [comment]
I am having this issue now. I could not find an update for this since it was first posted.

### This is the entity state:
````
temperature: 24.4
temperature_unit: °C
humidity: 37
pressure_unit: hPa
wind_bearing: WSW
wind_speed: 20
wind_speed_unit: km/h
visibility_unit: km
precipitation_unit: mm
forecast:
  - datetime: '2022-09-27T00:00:00+08:00'
    condition: clear-night
    templow: null
    precipitation_probability: 5
    temperature: 25
    precipitation: 0
  - datetime: '2022-09-28T00:00:00+08:00'
    condition: sunny
    templow: 10
    precipitation_probability: 5
    temperature: 27
    precipitation: 0
  - datetime: '2022-09-29T00:00:00+08:00'
    condition: sunny
    templow: 13
    precipitation_probability: 5
    temperature: 28
    precipitation: 0
  - datetime: '2022-09-30T00:00:00+08:00'
    condition: sunny
    templow: 15
    precipitation_probability: 5
    temperature: 28
    precipitation: 0
  - datetime: '2022-10-01T00:00:00+08:00'
    condition: sunny
    templow: 13
    precipitation_probability: 5
    temperature: 27
    precipitation: 0
  - datetime: '2022-10-02T00:00:00+08:00'
    condition: sunny
    templow: 12
    precipitation_probability: 30
    temperature: 24
    precipitation: 0
  - datetime: '2022-10-03T00:00:00+08:00'
    condition: sunny
    templow: 10
    precipitation_probability: 30
    temperature: 21
    precipitation: 1
  - datetime: '2022-10-04T00:00:00+08:00'
    condition: rainy
    templow: 9
    precipitation_probability: 60
    temperature: 19
    precipitation: 2
attribution: Data provided by the Australian Bureau of Meteorology
icon: mdi:weather-night
friendly_name: Deleted
````

### This is the output from https://api.weather.bom.gov.au/v1/locations/qd66rbb/forecasts/daily
`{"data":[{"rain":{"amount":{"min":0,"max":null,"lower_range":0,"upper_range":0,"units":"mm"},"chance":5,"precipitation_amount_25_percent_chance":0,"precipitation_amount_50_percent_chance":0,"precipitation_amount_75_percent_chance":0},"uv":{"category":"high","end_time":"2022-09-27T07:10:00Z","max_index":7,"start_time":"2022-09-27T00:50:00Z"},"astronomical":{"sunrise_time":"2022-09-26T22:00:52Z","sunset_time":"2022-09-27T10:16:00Z"},"date":"2022-09-26T16:00:00Z","temp_max":25,"temp_min":null,"extended_text":"Sunny. Light winds becoming southwesterly 15 to 20 km/h in the late afternoon then becoming light in the evening.","icon_descriptor":"clear","short_text":"Sunny.","surf_danger":null,"fire_danger":"No Rating","fire_danger_category":{"text":"No Rating","default_colour":null,"dark_mode_colour":null},"now":{"is_night":false,"now_label":"Max","later_label":"Overnight Min","temp_now":25,"temp_later":10}},{"rain":{"amount":{"min":0,"max":null,"lower_range":0,"upper_range":0,"units":"mm"},"chance":5,"precipitation_amount_25_percent_chance":0,"precipitation_amount_50_percent_chance":0,"precipitation_amount_75_percent_chance":0},"uv":{"category":"high","end_time":"2022-09-28T07:10:00Z","max_index":7,"start_time":"2022-09-28T01:00:00Z"},"astronomical":{"sunrise_time":"2022-09-27T21:59:32Z","sunset_time":"2022-09-28T10:16:37Z"},"date":"2022-09-27T16:00:00Z","temp_max":27,"temp_min":10,"extended_text":"Sunny. Light winds becoming east to northeasterly 15 to 20 km/h in the morning then tending east to southeasterly in the late afternoon.","icon_descriptor":"mostly_sunny","short_text":"Sunny.","surf_danger":null,"fire_danger":"Moderate","fire_danger_category":{"text":"Moderate","default_colour":"#64bf30","dark_mode_colour":"#64bf30"}},{"rain":{"amount":{"min":0,"max":null,"lower_range":0,"upper_range":0,"units":"mm"},"chance":5,"precipitation_amount_25_percent_chance":0,"precipitation_amount_50_percent_chance":0,"precipitation_amount_75_percent_chance":0},"uv":{"category":"high","end_time":"2022-09-29T07:10:00Z","max_index":7,"start_time":"2022-09-29T01:10:00Z"},"astronomical":{"sunrise_time":"2022-09-28T21:58:13Z","sunset_time":"2022-09-29T10:17:14Z"},"date":"2022-09-28T16:00:00Z","temp_max":28,"temp_min":13,"extended_text":"Sunny. Winds east to southeasterly 20 to 30 km/h.","icon_descriptor":"sunny","short_text":"Sunny.","surf_danger":null,"fire_danger":"Moderate","fire_danger_category":{"text":"Moderate","default_colour":"#64bf30","dark_mode_colour":"#64bf30"}},{"rain":{"amount":{"min":0,"max":null,"lower_range":0,"upper_range":0,"units":"mm"},"chance":5,"precipitation_amount_25_percent_chance":0,"precipitation_amount_50_percent_chance":0,"precipitation_amount_75_percent_chance":0},"uv":{"category":"high","end_time":"2022-09-30T07:20:00Z","max_index":7,"start_time":"2022-09-30T00:50:00Z"},"astronomical":{"sunrise_time":"2022-09-29T21:56:54Z","sunset_time":"2022-09-30T10:17:52Z"},"date":"2022-09-29T16:00:00Z","temp_max":28,"temp_min":15,"extended_text":"Sunny. Winds easterly 15 to 25 km/h turning southeasterly 15 to 20 km/h during the afternoon.","icon_descriptor":"sunny","short_text":"Sunny.","surf_danger":null,"fire_danger":"Moderate","fire_danger_category":{"text":"Moderate","default_colour":"#64bf30","dark_mode_colour":"#64bf30"}},{"rain":{"amount":{"min":0,"max":null,"lower_range":0,"upper_range":0,"units":"mm"},"chance":5,"precipitation_amount_25_percent_chance":0,"precipitation_amount_50_percent_chance":0,"precipitation_amount_75_percent_chance":0},"uv":{"category":null,"end_time":null,"max_index":null,"start_time":null},"astronomical":{"sunrise_time":"2022-09-30T21:55:35Z","sunset_time":"2022-10-01T10:18:30Z"},"date":"2022-09-30T16:00:00Z","temp_max":27,"temp_min":13,"extended_text":"Sunny. Winds easterly 15 to 20 km/h tending southeasterly 15 to 25 km/h during the day.","icon_descriptor":"sunny","short_text":"Sunny.","surf_danger":null,"fire_danger":null,"fire_danger_category":{"text":null,"default_colour":null,"dark_mode_colour":null}},{"rain":{"amount":{"min":0,"max":null,"lower_range":0,"upper_range":0,"units":"mm"},"chance":30,"precipitation_amount_25_percent_chance":0,"precipitation_amount_50_percent_chance":0,"precipitation_amount_75_percent_chance":0},"uv":{"category":null,"end_time":null,"max_index":null,"start_time":null},"astronomical":{"sunrise_time":"2022-10-01T21:54:17Z","sunset_time":"2022-10-02T10:19:09Z"},"date":"2022-10-01T16:00:00Z","temp_max":24,"temp_min":12,"extended_text":"Sunny morning. Medium (40%) chance of showers, most likely later in the day. Winds east to southeasterly 15 to 25 km/h.","icon_descriptor":"mostly_sunny","short_text":"Possible shower.","surf_danger":null,"fire_danger":null,"fire_danger_category":{"text":null,"default_colour":null,"dark_mode_colour":null}},{"rain":{"amount":{"min":0,"max":1,"lower_range":0,"upper_range":1,"units":"mm"},"chance":30,"precipitation_amount_25_percent_chance":1,"precipitation_amount_50_percent_chance":0,"precipitation_amount_75_percent_chance":0},"uv":{"category":null,"end_time":null,"max_index":null,"start_time":null},"astronomical":{"sunrise_time":"2022-10-02T21:52:59Z","sunset_time":"2022-10-03T10:19:47Z"},"date":"2022-10-02T16:00:00Z","temp_max":21,"temp_min":10,"extended_text":"Slight (30%) chance of a shower during the morning. Mostly sunny day. Winds east to southeasterly 15 to 20 km/h.","icon_descriptor":"mostly_sunny","short_text":"Mostly sunny.","surf_danger":null,"fire_danger":null,"fire_danger_category":{"text":null,"default_colour":null,"dark_mode_colour":null}},{"rain":{"amount":{"min":0,"max":2,"lower_range":0,"upper_range":2,"units":"mm"},"chance":60,"precipitation_amount_25_percent_chance":2,"precipitation_amount_50_percent_chance":0,"precipitation_amount_75_percent_chance":0},"uv":{"category":null,"end_time":null,"max_index":null,"start_time":null},"astronomical":{"sunrise_time":"2022-10-03T21:51:41Z","sunset_time":"2022-10-04T10:20:26Z"},"date":"2022-10-03T16:00:00Z","temp_max":19,"temp_min":9,"extended_text":null,"icon_descriptor":"shower","short_text":null,"surf_danger":null,"fire_danger":null,"fire_danger_category":{"text":null,"default_colour":null,"dark_mode_colour":null}}],"metadata":{"response_timestamp":"2022-09-27T07:40:44Z","issue_time":"2022-09-27T07:10:57Z","next_issue_time":"2022-09-27T08:00:00Z","forecast_region":"Perth","forecast_type":"metropolitan","copyright":"This Application Programming Interface (API) is owned by the Bureau of Meteorology (Bureau). You must not use, copy or share it. Please contact us for more information on ways in which you can access our data. Follow this link http://www.bom.gov.au/inside/contacts.shtml to view our contact details."}}`

### Here is output from https://api.weather.bom.gov.au/v1/locations/qd66rb/observations
`{"metadata":{"response_timestamp":"2022-09-27T07:41:37Z","issue_time":"2022-09-27T07:31:01Z","observation_time":"2022-09-27T07:30:00Z","copyright":"This Application Programming Interface (API) is owned by the Bureau of Meteorology (Bureau). You must not use, copy or share it. Please contact us for more information on ways in which you can access our data. Follow this link http://www.bom.gov.au/inside/contacts.shtml to view our contact details."},"data":{"temp":24.4,"temp_feels_like":20.3,"wind":{"speed_kilometre":20,"speed_knot":11,"direction":"WSW"},"gust":{"speed_kilometre":24,"speed_knot":13},"max_gust":{"speed_kilometre":30,"speed_knot":16,"time":"2022-09-27T07:26:00Z"},"max_temp":{"time":"2022-09-27T06:21:00Z","value":25.5},"min_temp":{"time":"2022-09-26T21:07:00Z","value":6.8},"rain_since_9am":0,"humidity":37,"station":{"bom_id":"009021","name":"Perth Airport","distance":3762}}}`
